/** Every user-facing string lives here, never inline in components. */
export const en = {
  appTitle: 'Universe Explorer',
  wholeView: 'Whole view',
  cardSolarSystemHello:
    'This is our solar system: one star, the Sun, with eight planets going around it. Tap a planet or its name to fly there.',
  cardSolarSystemFact1: 'Our solar system formed about 4.6 billion years ago.',
  cardSolarSystemFact2: 'Planets close to the Sun race around it. Mercury is the fastest of all.',
  cardSolarSystemFact3:
    'Planets far from the Sun take a very long time. Neptune needs 165 Earth years for one trip.',
  cardSunHello: 'The Sun is a star: a hot, glowing ball of gas in the middle of our solar system.',
  cardSunFact1: 'About 1.3 million Earths would fit inside the Sun.',
  cardSunFact2:
    'The part of the Sun we can see is about 5,500 °C. Deep in its middle it is about 15 million °C.',
  cardSunFact3:
    'The Sun does not spin as one solid ball. Its middle turns faster than its top and bottom.',
  cardMercuryHello: 'Mercury is the smallest planet and the closest to the Sun.',
  cardMercuryFact1: 'Mercury is the fastest planet. It zips around the Sun in just 88 Earth days.',
  cardMercuryFact2: 'It is covered in craters, a lot like our Moon.',
  cardMercuryFact3:
    'Mercury has no blanket of air to hold in heat, so its nights can drop to -180 °C.',
  cardVenusHello: 'Venus is the hottest planet. Its thick air traps heat like a blanket.',
  cardVenusFact1: 'It is about 467 °C on Venus, hot enough to melt lead.',
  cardVenusFact2: 'Venus spins backwards. There, the Sun comes up in the west.',
  cardVenusFact3: 'After the Sun and the Moon, Venus is the brightest thing in our sky.',
  cardEarthHello: 'Earth is our home. It is the only place we know of with living things.',
  cardEarthFact1: 'Most of Earth is covered in water.',
  cardEarthFact2: 'Earth is tilted, and that tilt gives us the seasons.',
  cardEarthFact3:
    'Earth is the only planet whose English name does not come from an old Greek or Roman story.',
  cardMoonHello: 'The Moon goes around Earth about once every 27 days.',
  cardMoonFact1:
    'We always see the same side of the Moon. Its far side can never be seen from Earth.',
  cardMoonFact2:
    'In sunshine the Moon heats up to about 127 °C. In the dark it drops to about -173 °C.',
  cardMoonFact3: 'The Moon is slowly drifting away from Earth, about an inch (2.5 cm) every year.',
  cardMarsHello: 'Mars is the Red Planet. Rusty iron in its dirt makes it look red.',
  cardMarsFact1: 'Mars has the biggest volcano in the solar system. It is called Olympus Mons.',
  cardMarsFact2: 'Mars is the only planet where we have sent rovers to drive around.',
  cardMarsFact3: 'Mars has two small moons, named Phobos and Deimos.',
  cardJupiterHello: 'Jupiter is the biggest planet in our solar system.',
  cardJupiterFact1: 'If Jupiter were an empty shell, about 1,000 Earths could fit inside.',
  cardJupiterFact2:
    'The Great Red Spot is a giant storm, bigger than Earth. It has been blowing for hundreds of years.',
  cardJupiterFact3:
    'Jupiter has the shortest day of any planet. It spins all the way round in about 10 hours.',
  cardSaturnHello: 'Saturn is the second-biggest planet, a giant ball made mostly of gas.',
  cardSaturnFact1:
    "The pieces in Saturn's rings go from tiny icy grains to chunks as big as a house.",
  cardSaturnFact2:
    'Saturn is so light for its size that it could float in a bathtub, if there were one big enough.',
  cardSaturnFact3: 'Saturn has far more moons than any other planet.',
  cardUranusHello: 'Uranus spins on its side, going around the Sun like a rolling ball.',
  cardUranusFact1: 'Uranus is very cold. Its air can drop to about -224 °C.',
  cardUranusFact2: 'Its blue-green colour comes from a gas called methane.',
  cardUranusFact3: 'Uranus has 13 faint rings.',
  cardNeptuneHello: 'Neptune is the farthest planet from the Sun. It is dark, cold and very windy.',
  cardNeptuneFact1: 'Neptune is the windiest planet. Its winds blow at more than 2,000 km an hour.',
  cardNeptuneFact2:
    'Neptune was the first planet found by doing maths, not by spotting it in the sky.',
  cardNeptuneFact3: 'Neptune has gone around the Sun just once since it was found in 1846.',
  names: 'Names',
  compare: 'Compare',
  compareClose: 'Close compare',
  compareSizes: 'How big?',
  compareDistances: 'How far?',
  compareSizesLead: 'The planets side by side, at their real sizes next to each other.',
  compareSunNote: 'The Sun is not here: it is {times} times as wide as {planet} and would not fit.',
  compareDistancesLead:
    'The planets in a line, at their real distances from the Sun. Slide along to reach them all.',
  compareDistancesNote:
    'Only the gaps are real here. At this scale even Jupiter would be far smaller than one dot.',
  places: 'Places to explore',
  closeCard: 'Close card',
  readToMe: 'Read it to me',
  stopReading: 'Stop reading',
  coolFacts: 'Cool facts',
  aboutTheGlobe: 'About this globe',
  nameSolarSystem: 'Our Solar System',
  nameSun: 'The Sun',
  nameMoon: 'The Moon',
  eyebrowSolarSystem: 'Welcome, space explorer',
  eyebrowStar: 'Star · the middle of our solar system',
  eyebrowPlanet: 'Planet · {place} from the Sun',
  eyebrowMoon: 'Moon · goes around {parent}',
  eyebrowDwarfPlanet: 'Dwarf planet · goes around the Sun',
  helloDwarfPlanet: '{name} is a dwarf planet.',
  cardAsteroidBeltHello:
    'The asteroid belt is a wide ring of space rocks between Mars and Jupiter.',
  cardAsteroidBeltFact1: 'Asteroids are rocky bits left over from when the solar system was made.',
  cardAsteroidBeltFact2: 'The biggest asteroid is Vesta. It is about 530 km across.',
  cardAsteroidBeltFact3: 'Most asteroids are lumpy, not round, and many are covered in craters.',
  cardKuiperBeltHello: 'The Kuiper Belt is a huge doughnut of icy worlds, far out past Neptune.',
  cardKuiperBeltFact1:
    "It starts at Neptune's orbit, about 30 times as far from the Sun as Earth is.",
  cardKuiperBeltFact2: 'Scientists think it holds millions of small, icy objects.',
  cardKuiperBeltFact3: 'Some of its worlds, like Pluto, are more than 1,000 km wide.',
  cardHalleyHello: "Halley's Comet is a lump of ice, frozen gas and dust that goes around the Sun.",
  cardHalleyFact1:
    'When a comet gets near the Sun it warms up and grows a cloud around it, called a coma.',
  cardHalleyFact2:
    'Sunlight and wind from the Sun blow dust and gas off the comet, making a long, bright tail.',
  cardHalleyFact3: "Halley's Comet never gets closer to the Sun than 89 million km.",
  nameHalley: "Halley's Comet",
  eyebrowComet: 'Comet · goes around the Sun',
  cometNote:
    'The tail is drawn, not photographed. It points away from the Sun, as real tails do, but its length is not to scale. The path shown is right for 1950 to 2050; earlier visits came at slightly different times.',
  statClosest: 'Closest to the Sun',
  valueTimesEarthOne: "{n} times Earth's distance",
  conceptStarTitle: 'What is a star?',
  conceptStarText: 'A star is a huge, hot, glowing ball of gas. The Sun is the star closest to us.',
  conceptPlanetTitle: 'What is a planet?',
  conceptPlanetText:
    'A planet is a big, round world that goes around a star and has cleared other big things out of its path.',
  conceptDwarfPlanetTitle: 'What is a dwarf planet?',
  conceptDwarfPlanetText:
    'A dwarf planet goes around the Sun and is nearly round, but it shares its path with other things.',
  conceptMoonTitle: 'What is a moon?',
  conceptMoonText: 'A moon is a natural world that goes around a planet.',
  conceptAsteroidTitle: 'What is an asteroid?',
  conceptAsteroidText: 'An asteroid is a rocky bit left over from when the solar system was made.',
  conceptCometTitle: 'What is a comet?',
  conceptCometText:
    'A comet is an icy leftover from when the solar system was new. Near the Sun it grows a tail.',
  conceptBeltTitle: 'What is a belt?',
  conceptBeltText:
    'A belt is a wide ring made of a great many small worlds, all going around the Sun.',
  pictureAltPleiades:
    'A wispy grey cloud of dust lit by a bright star of the Pleiades, which is just outside the picture.',
  namePleiades: 'The Pleiades',
  cardPleiadesHello:
    'The Pleiades is a bright group of stars that you can see without a telescope.',
  cardPleiadesFact1: 'It holds more than a thousand stars, held loosely together by gravity.',
  cardPleiadesFact2: 'People also call it the Seven Sisters.',
  cardPleiadesFact3:
    'It is about 445 light-years away, but scientists do not all agree on that number.',
  pictureAltOrionNebula:
    'A huge glowing cloud of pink, orange and blue gas and dust, with bright young stars inside it.',
  nameOrionNebula: 'The Orion Nebula',
  cardOrionNebulaHello:
    'The Orion Nebula is a giant cloud of gas and dust where new stars are being made.',
  cardOrionNebulaFact1: 'You can spot it without a telescope on a dark night.',
  cardOrionNebulaFact2: 'It is the closest big star-making cloud to Earth.',
  cardOrionNebulaFact3: 'Four big, young stars in its middle shape the cloud.',
  pictureAltCrabNebula:
    'A tangled cloud of orange and blue threads of gas, left behind by a star that exploded.',
  nameCrabNebula: 'The Crab Nebula',
  cardCrabNebulaHello: 'The Crab Nebula is what is left of a star that exploded.',
  cardCrabNebulaFact1:
    'People in China saw the explosion in the year 1054. It was bright enough to see in the daytime.',
  cardCrabNebulaFact2: 'The cloud is about six light-years wide.',
  cardCrabNebulaFact3: 'In its middle is the squashed core of the star, spinning very fast.',
  pictureAltAndromeda:
    'A long, tilted spiral galaxy glowing with millions of stars, with dark lanes of dust winding through it.',
  nameAndromeda: 'The Andromeda Galaxy',
  cardAndromedaHello: 'The Andromeda Galaxy is the nearest big galaxy to our own, the Milky Way.',
  cardAndromedaFact1: 'You can see it with your own eyes on a dark night.',
  cardAndromedaFact2:
    'This picture shows the glow of 200 million stars, and that is only some of them.',
  cardAndromedaFact3:
    'The picture is made of more than 600 Hubble photos joined together. It took over 10 years.',
  pictureAltM87:
    'A huge, round, glowing yellow galaxy with a thin blue jet shooting out from its middle.',
  nameM87: 'The M87 Galaxy',
  cardM87Hello: 'M87 is a giant galaxy with several trillion stars.',
  cardM87Fact1: 'A giant black hole sits in its middle.',
  cardM87Fact2: 'Our Milky Way has a few hundred billion stars. M87 has far more.',
  cardM87Fact3:
    'The blue streak in the picture is a jet of tiny particles flying out at nearly the speed of light.',
  conceptNebulaTitle: 'What is a nebula?',
  conceptNebulaText:
    'A nebula is a giant cloud of gas and dust in space. New stars can be born inside one.',
  conceptStarClusterTitle: 'What is a star cluster?',
  conceptStarClusterText: 'A star cluster is a group of stars that stay together, held by gravity.',
  conceptGalaxyTitle: 'What is a galaxy?',
  conceptGalaxyText:
    'A galaxy is an enormous family of stars: billions of them, all held together by gravity.',
  sceneControl: 'Where to explore',
  sceneSolar: 'Solar System',
  sceneDeep: 'Deep Space',
  eyebrowDeep: '{kind} · {distance} away',
  kindNebula: 'Nebula',
  kindStarCluster: 'Star cluster',
  kindGalaxy: 'Galaxy',
  kindStar: 'Star',
  kindBlackHole: 'Black hole',
  kindExoplanet: 'Planets of another star',
  eyebrowHome: '{kind} · our home',
  pictureAltProximaCentauri:
    'A single bright white star with four spikes of light, on a black sky dotted with fainter stars.',
  nameProximaCentauri: 'Proxima Centauri',
  cardProximaCentauriHello: 'Proxima Centauri is the closest star to us, apart from the Sun.',
  cardProximaCentauriFact1: 'It is just over four light-years away.',
  cardProximaCentauriFact2: 'Even so, it is too dim to see with your eyes alone.',
  cardProximaCentauriFact3: 'It is small for a star: only about an eighth as heavy as the Sun.',
  pictureAltTrappist1:
    "An artist's drawing of seven small planets in a row, in browns, greys and blues, beside a dim red star.",
  nameTrappist1: 'The TRAPPIST-1 Planets',
  cardTrappist1Hello: 'TRAPPIST-1 is a star with seven rocky planets going around it.',
  cardTrappist1Fact1: 'It is about 40 light-years away.',
  cardTrappist1Fact2: 'All seven planets might have water.',
  cardTrappist1Fact3:
    "Nobody has seen these planets up close. The picture is an artist's idea of how they may look.",
  pictureAltMilkyWay:
    "An artist's drawing of our galaxy from above: a spiral of stars with a bright bar in the middle, and a label showing where the Sun is.",
  nameMilkyWay: 'The Milky Way',
  cardMilkyWayHello: 'The Milky Way is our home galaxy. The Sun is one of its stars.',
  cardMilkyWayFact1:
    'It is a spiral with two big arms that wrap around a bar of stars in the middle.',
  cardMilkyWayFact2:
    'Our Sun sits beside a small arm called the Orion Arm. Look for the word Sun in the picture.',
  cardMilkyWayFact3:
    "This is an artist's drawing. We live inside the Milky Way, so nobody can photograph all of it.",
  pictureAltM87BlackHole:
    'A fuzzy, glowing orange ring around a dark middle, on a black background.',
  nameM87BlackHole: 'The M87 Black Hole',
  cardM87BlackHoleHello: 'This is the first picture ever taken of a black hole.',
  cardM87BlackHoleFact1:
    'It sits in the middle of the galaxy M87, about 55 million light-years away.',
  cardM87BlackHoleFact2: 'The glow is hot gas swirling around the black hole.',
  cardM87BlackHoleFact3: 'There is a giant black hole in the middle of our own galaxy too.',
  conceptBlackHoleTitle: 'What is a black hole?',
  conceptBlackHoleText:
    'A black hole is a place where gravity pulls so hard that nothing can get out, not even light.',
  conceptExoplanetTitle: 'What is an exoplanet?',
  conceptExoplanetText: 'An exoplanet is a planet that goes around a star other than our Sun.',
  statHowFar: 'How far away',
  statLightLeft: 'The light you see left it',
  statWide: 'Width',
  valueLightYears: '{n} light-years',
  valueMillionLightYears: '{n} million light-years',
  valueYearsAgo: '{n} years ago',
  valueMillionYearsAgo: '{n} million years ago',
  pictureCredit: 'Picture: {credit}',
  eyebrowAsteroid: 'Asteroid · goes around the Sun',
  helloAsteroid: '{name} is an asteroid.',
  eyebrowBelt: 'Belt · many small worlds going around the Sun',
  beltNote:
    'Each dot is a real object on its real path. The dots are drawn much bigger than the objects really are.',
  statDots: 'Dots drawn here',
  statBeltSpan: 'From the Sun',
  valueTimesEarth: "{from} to {to} times Earth's distance",
  ordinals: '1st 2nd 3rd 4th 5th 6th 7th 8th',
  statPlanets: 'Planets',
  statStars: 'Stars',
  statSunlight: 'Sunlight reaches Earth in',
  statSpin: 'One spin',
  statYear: 'One trip around the Sun',
  statMoons: 'Moons',
  statWidth: 'Width',
  statSurface: 'Surface',
  statFromParent: 'From {parent}',
  statTripAround: 'One trip around {parent}',
  helloMoon: '{name} is a moon of {parent}.',
  valueKmWide: '{n} km wide',
  valueHours: '{n} hours',
  valueEarthDays: '{n} Earth days',
  valueEarthYears: '{n} Earth years',
  valueMinutes: 'about {n} minutes',
  valueEarths: '{n} Earths wide',
  valueKm: '{n} km',
  valueCelsius: 'about {n} °C',
  valueOneSun: '1, the Sun',
  goTo: 'Go to',
  speedControl: 'How fast time goes',
  speedPause: 'Pause',
  speedSlow: 'Slow',
  speedNormal: 'Normal',
  speedFast: 'Fast',
  today: 'Today',
  rate: 'One Earth year takes {seconds} seconds',
  ratePaused: 'Time is stopped',
  dateLimit: 'Our maps of the orbits only go from {from} to {to}, so time stops here.',
  scaleControl: 'How big and how far things are drawn',
  scaleOptionTrue: 'Real',
  scaleOptionTrueSizes: 'Real sizes',
  scaleOptionEasy: 'Easy view',
  scaleLabelTrue: 'Real sizes and real distances.',
  scaleLabelTrueSizes:
    'Planets are the right size next to each other. They are really much farther apart.',
  scaleLabelEasy: 'Drawn bigger and closer so you can see everything.',
  mapAltMercury: "A map of Mercury's surface: grey and covered in craters.",
  mapAltVenus: 'A map of the ground on Venus made with radar, with colours added by scientists.',
  mapAltEarth:
    'A map of Earth from space: blue oceans, green and brown land, white ice at the poles.',
  mapAltMoon: "A map of the Moon's surface: grey with darker patches and many craters.",
  mapAltMars: 'A map of Mars: rusty orange with darker regions and white ice at the poles.',
  mapAltJupiter: "A map of Jupiter's clouds in cream and brown stripes, with the Great Red Spot.",
  mapAltSaturn: "An artist's drawing of Saturn's pale yellow cloud bands.",
  mapAltUranus: "An artist's drawing of Uranus: smooth pale blue-green.",
  mapAltNeptune: "An artist's drawing of Neptune: deep blue with a few white clouds.",
  mediaKindComposite: 'Made from many pictures joined together.',
  mediaKindFalseColour: 'Colours added by scientists.',
  mediaKindArtistConcept: "An artist's drawing, not a photo.",
  mediaKindSimulation: 'A computer simulation, not a photo.',
  mediaKindDiagram: 'A diagram, not a photo.',
} as const;

export type StringKey = keyof typeof en;
